/*****************************************************************************
* Model: stirrer.qm
* File:  ../src/stirrer.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${../src::stirrer.c} .....................................................*/
// #include "qpc.h"
#include "stirrer.h"
// #include "bsp.h"

Q_DEFINE_THIS_FILE

/*..........................................................................*/
int main() {
 static QEvt const* frontQueueSto[5];
// static QEvt const* controlQueueSto[5];

 static QF_MPOOL_EL(QEvt)           smlPoolSto[10];
 static QF_MPOOL_EL(TachoEvt)       medPoolSto[10];

    /* explicitly invoke the active objects' ctors... */
    Front_ctor();
//    Control_ctor();

    QF_init();    /* initialize the framework and the underlying RT kernel */
    BSP_init();   /* initialize the Board Support Package */

    /* send object dictionaries for event queues... */
    QS_OBJ_DICTIONARY(frontQueueSto);
//    QS_OBJ_DICTIONARY(controlQueueSto);

    /* send object dictionaries for event pools... */
    QS_OBJ_DICTIONARY(smlPoolSto);
//    QS_OBJ_DICTIONARY(medPoolSto);




    /* initialize the event pools... */
    QF_poolInit(smlPoolSto, sizeof(smlPoolSto), sizeof(smlPoolSto[0]));
    QF_poolInit(medPoolSto, sizeof(medPoolSto), sizeof(medPoolSto[0]));

    /* send object dictionaries for event queues... */
//    QS_OBJ_DICTIONARY(frontQueueSto);
//    QS_OBJ_DICTIONARY(controlQueueSto);

    /* send object dictionaries for event pools... */
//    QS_OBJ_DICTIONARY(smlPoolSto);
//    QS_OBJ_DICTIONARY(medPoolSto);



    /* start the active objects... */
    QACTIVE_START(AO_Front,
                  2U,                /* QP priority */
                  frontQueueSto,  Q_DIM(frontQueueSto), /* evt queue */
                  (void *)0, 0U,     /* no per-thread stack */
                  (QEvt *)0);        /* no initialization event */

#if 0
    QACTIVE_START(AO_Control,
                  3U,                /* QP priority */
                  controlQueueSto,    Q_DIM(controlQueueSto), /* evt queue */
                  (void *)0, 0U,     /* no per-thread stack */
                  (QEvt *)0);        /* no initialization event */

#endif    // 0

    return QF_run(); /* run the QF application */
}
